[install]
linker = "hoisted"
linkWorkspacePackages = true

[test]
pathIgnorePatterns = [
    "**/*.integration.test.*", 
    "freebuff/e2e/**", 
    "agents/librarian/**"   # Comment this if you have CODEBUFF_API_KEY
    ]
preload = ["./sdk/test/setup-env.ts"]
